services:
  db:
    image: postgres:15
    container_name: blueprint-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    container_name: blueprint-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
    depends_on:
      - db

  client:
    container_name: blueprint-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  pgdata:
  client_node_modules:
